Base structure
SheetalAlbiorix/montra pull request #1
Opened 2024-09-27 13:19 UTC by JhanviAlbiorix

2024-09-30 10:40 UTC, SohanAlbiorix requested changes

2024-09-30 10:40 UTC, SohanAlbiorix commented on lib/src/presentation/core/utils/helper/shared_preference_helper.dart
empty file exists

2024-09-30 10:40 UTC, SohanAlbiorix commented on lib/src/presentation/core/utils/helper/validators.dart
commented file exists

2024-09-30 10:40 UTC, SohanAlbiorix commented on lib/src/presentation/core/utils/widgets/custom_text_form_field.dart
empty file exists

2024-09-30 10:40 UTC, SohanAlbiorix commented on pubspec.lock
.lock file should be not in git repo, please remove this and add it to .gitignore

2024-09-30 10:40 UTC, SohanAlbiorix commented on web/index.html
web index file? Have we added support for the web?

2024-09-30 10:40 UTC, SohanAlbiorix commented on lib/src/presentation/core/utils/widgets/custom_button.dart
I can see most of the properties are passing, so it doesn't make sense to create a custom button.

2024-10-01 09:10 UTC, SohanAlbiorix commented on lib/src/presentation/core/utils/helper/base_validations_strings.dart
I believe your app supports localisation, please update this file once you implemented it. It is okay for now.

2024-10-01 09:13 UTC, JhanviAlbiorix commented on lib/src/presentation/core/utils/helper/base_validations_strings.dart
I have made the initial commit considering the structure as functionalities are asked to be ignored for now as per yesterday's discussion.

2024-10-01 09:14 UTC, SohanAlbiorix approved these changes

2024-10-01 09:14 UTC, SohanAlbiorix commented on pubspec.lock
This file should be removed from the version control, you have already added it to gitignore.

2024-10-03 07:01 UTC, merged